---
- hosts: all
  become: yes

  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Deploy Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'docker'
              static_configs:
                - targets: ['localhost:9323']

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

